2021-08-02 16:48:54,357 parse_helper.py[line:556] ERROR list index out of range
